version: '3'
volumes:
  pgdata:
  static_files:
services:
  python:
    #image: python:3.7
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=django_tutorial.settings.prod
    volumes:
      - .:/app
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 django_tutorial.wsgi -b 0.0.0.0:8000
  postgres:
    image: postgres:12.2
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Lfagoew64
    volumes:
      - pgdata:/var/lib/postgresql/data/
  nginx:
    #image: nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - '8080:80'
