# Generated by Django 2.2.6 on 2019-10-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macronutrients',
            name='energy_content',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
