# Generated by Django 2.2.6 on 2019-10-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0003_auto_20191017_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(max_length=30)),
                ('gram_equivalent', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Measurements',
            },
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Macronutrients',
            new_name='Macronutrient',
        ),
        migrations.RenameModel(
            old_name='Steps',
            new_name='RecipeStep',
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
        migrations.AlterField(
            model_name='quantity',
            name='measurement',
            field=models.ManyToManyField(to='madplan.Measurement'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_description',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='madplan.RecipeDescription'),
        ),
        migrations.AlterField(
            model_name='recipedescription',
            name='recipe_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
