# Generated by Django 2.2.6 on 2019-10-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0004_auto_20191017_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='recipe',
        ),
        migrations.AddField(
            model_name='quantity',
            name='recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='madplan.Recipe'),
        ),
    ]
