# Generated by Django 2.2.6 on 2019-10-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0009_auto_20191017_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='madplan.Recipe'),
        ),
    ]
