# Generated by Django 2.2.6 on 2019-10-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0011_auto_20191017_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='madplan.RecipeDescription'),
        ),
    ]
