# Generated by Django 2.2.6 on 2019-10-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0012_auto_20191017_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='alcohol_content_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrate_content_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='energy_content_Kcal',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_content_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fibre_content_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_content_g',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
