# Generated by Django 2.2.6 on 2019-10-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0013_auto_20191017_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='alcohol_content_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrate_content_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='energy_content_Kcal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_content_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fibre_content_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='madplan.IngredientCategory'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_content_g',
            field=models.FloatField(null=True),
        ),
    ]
