# Generated by Django 2.2.6 on 2020-04-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0014_auto_20191017_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'verbose_name_plural': 'RecipeSteps'},
        ),
    ]
